services:
  litellm:
    image: ghcr.io/berriai/litellm:1.100.0
    environment:
      - GROQ_API_KEY
    ports:
      - "4000:4000"
    command:
      - "--config"
      - "/app/config.yaml"
      - "--port"
      - "4000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ${PWD}/docker/config.yaml:/app/config.yaml:ro
